/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LaunchverseRouteImport } from './routes/launchverse'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as RainwaterRouteImport } from './routes/rainwater'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RoRejectRouteImport } from './routes/ro-reject'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchverseRoute = LaunchverseRouteImport.update({
  id: '/launchverse',
  path: '/launchverse',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const RainwaterRoute = RainwaterRouteImport.update({
  id: '/rainwater',
  path: '/rainwater',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RoRejectRoute = RoRejectRouteImport.update({
  id: '/ro-reject',
  path: '/ro-reject',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/launchverse': typeof LaunchverseRoute
  '/maintenance': typeof MaintenanceRoute
  '/rainwater': typeof RainwaterRoute
  '/recommendations': typeof RecommendationsRoute
  '/ro-reject': typeof RoRejectRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/launchverse': typeof LaunchverseRoute
  '/maintenance': typeof MaintenanceRoute
  '/rainwater': typeof RainwaterRoute
  '/recommendations': typeof RecommendationsRoute
  '/ro-reject': typeof RoRejectRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/devices': typeof DevicesRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/launchverse': typeof LaunchverseRoute
  '/maintenance': typeof MaintenanceRoute
  '/rainwater': typeof RainwaterRoute
  '/recommendations': typeof RecommendationsRoute
  '/ro-reject': typeof RoRejectRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/devices'
    | '/help'
    | '/history'
    | '/launchverse'
    | '/maintenance'
    | '/rainwater'
    | '/recommendations'
    | '/ro-reject'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/devices'
    | '/help'
    | '/history'
    | '/launchverse'
    | '/maintenance'
    | '/rainwater'
    | '/recommendations'
    | '/ro-reject'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/devices'
    | '/help'
    | '/history'
    | '/launchverse'
    | '/maintenance'
    | '/rainwater'
    | '/recommendations'
    | '/ro-reject'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DevicesRoute: typeof DevicesRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  LaunchverseRoute: typeof LaunchverseRoute
  MaintenanceRoute: typeof MaintenanceRoute
  RainwaterRoute: typeof RainwaterRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RoRejectRoute: typeof RoRejectRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchverse': {
      id: '/launchverse'
      path: '/launchverse'
      fullPath: '/launchverse'
      preLoaderRoute: typeof LaunchverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rainwater': {
      id: '/rainwater'
      path: '/rainwater'
      fullPath: '/rainwater'
      preLoaderRoute: typeof RainwaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ro-reject': {
      id: '/ro-reject'
      path: '/ro-reject'
      fullPath: '/ro-reject'
      preLoaderRoute: typeof RoRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DevicesRoute: DevicesRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  LaunchverseRoute: LaunchverseRoute,
  MaintenanceRoute: MaintenanceRoute,
  RainwaterRoute: RainwaterRoute,
  RecommendationsRoute: RecommendationsRoute,
  RoRejectRoute: RoRejectRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
